// -------------- STUDIO ASSET MANIFEST --------------
// Typed central registry for the original static visual system (generated by
// scripts/generate-static-assets.mjs from scripts/asset-lib.mjs). One source
// of truth for path, intrinsic dimensions, alt text, demo status and caption
// so components never hard-code image paths.
//
// SCOPE: brand / service / process / about / insight assets live here.
// Case-study media stays colocated with its content in src/lib/caseStudies/*
// (the established `CaseStudyMedia` pattern) — see docs/UI-FORGE-ASSET-SYSTEM.md.
//
// Every asset is STATIC. No animation anywhere in the set.

export type StudioAssetCategory = 'brand' | 'project' | 'insight' | 'service' | 'process' | 'about';

export type StudioAsset = {
  /** Public path under /static, or absolute URL. */
  src: string;
  alt: string;
  /** Intrinsic dimensions — required for CLS-safe next/image layout. */
  width: number;
  height: number;
  category: StudioAssetCategory;
  /** Clearly-fictional demonstration artwork. */
  isDemo?: boolean;
  caption?: string;
};

/** True for vector assets that must be served with next/image `unoptimized`. */
export const isVector = (asset: Pick<StudioAsset, 'src'>): boolean => asset.src.endsWith('.svg');

// --- Brand -----------------------------------------------------------------

export const HOMEPAGE_SIGNATURE: StudioAsset = {
  src: '/static/brand/homepage-signature.svg',
  width: 1600,
  height: 1000,
  category: 'brand',
  alt: "UI Forge Studio's approach as one system: a browser-framed design canvas with an editorial serif headline and modular grid, joined by the forge-spark mark to a build specimen showing the type scale, colour palette and design tokens.",
};

export const START_PROJECT_VISUAL: StudioAsset = {
  src: '/static/brand/start-a-project.svg',
  width: 1000,
  height: 760,
  category: 'brand',
  alt: 'How a UI Forge enquiry works: a three-step path from brief, to a recommended approach, to a clear proposal.',
};

// --- Services (keyed by the exact SERVICE_CATEGORIES name) -----------------

export const SERVICE_ASSETS: Record<string, StudioAsset> = {
  'Web design & development': {
    src: '/static/services/websites.svg',
    width: 1200,
    height: 750,
    category: 'service',
    alt: 'A website project shown as page hierarchy and responsive architecture: a desktop layout and a mobile layout beside a site tree branching from Home to Work, Services and Insights, with responsive breakpoints.',
  },
  'Website redesign': {
    src: '/static/services/landing-pages.svg',
    width: 1200,
    height: 750,
    category: 'service',
    alt: 'A website redesign shown as structure and conversion path: hero, evidence, offer and call-to-action zones, with a current-state-to-improved-journey route.',
  },
  'Shopify development': {
    src: '/static/services/ecommerce.svg',
    width: 1200,
    height: 750,
    category: 'service',
    alt: 'An e-commerce build shown as one system: linked product, cart and checkout screens flowing left to right.',
  },
  'HubSpot websites': {
    src: '/static/services/landing-pages.svg',
    width: 1200,
    height: 750,
    category: 'service',
    alt: 'A HubSpot website and campaign system shown as reusable page sections connected to a lead-generation journey.',
  },
  'Web applications': {
    src: '/static/services/digital-products.svg',
    width: 1200,
    height: 750,
    category: 'service',
    alt: 'A digital product shown as an application shell: a sidebar and top bar around a draft-to-review-to-ship workflow, beside a component library.',
  },
  'Mobile applications': {
    src: '/static/services/mobile-apps.svg',
    width: 1200,
    height: 750,
    category: 'service',
    alt: 'A mobile application shown as one interface system: navigation, list and detail phone screens beside a shared component kit.',
  },
  'Website maintenance': {
    src: '/static/services/ongoing-care.svg',
    width: 1200,
    height: 750,
    category: 'service',
    alt: 'Ongoing care shown as monitoring and maintenance: a status board of healthy checks, a release timeline and a maintenance-and-support list.',
  },
};

// --- Process ---------------------------------------------------------------

export const PROCESS_MAP: StudioAsset = {
  src: '/static/process/project-map.svg',
  width: 1600,
  height: 680,
  category: 'process',
  alt: 'The seven-phase UI Forge process along one connected line: Discover, Define and Design (design), Build, Test and Launch (development), and Support (care).',
};

// --- About -----------------------------------------------------------------

export const ABOUT_ARTEFACTS: StudioAsset = {
  src: '/static/about/studio-artefacts.svg',
  width: 1080,
  height: 1350,
  category: 'about',
  alt: 'Studio artefacts in place of a portrait: a website frame, a type specimen, a modular grid and a panel of build tokens — evidence of a founder-led practice.',
};

// --- Insight covers (keyed by article slug) --------------------------------
// `hero` is the 3:2 on-page cover (SVG, rendered unoptimized). `ogImage` is a
// rasterised 1200x630 PNG — social platforms do not render SVG og:image.

export type InsightCover = { hero: StudioAsset; ogImage: string };

export const INSIGHT_COVERS: Record<string, InsightCover> = {
  'what-affects-the-cost-of-a-website': {
    hero: {
      src: '/static/insights/website-cost-cover.svg',
      width: 1200,
      height: 800,
      category: 'insight',
      alt: 'Cover for “What affects the cost of a website”: a scope-drives-cost diagram with scope bars for pages, features, content and integrations against a lower-to-higher cost axis.',
    },
    ogImage: '/static/insights/website-cost-og.png',
  },
  'website-ownership-and-hosting-explained': {
    hero: {
      src: '/static/insights/ownership-hosting-cover.svg',
      width: 1200,
      height: 800,
      category: 'insight',
      alt: 'Cover for “Website ownership and hosting explained”: a layered diagram of the domain, hosting, code and content layers you own.',
    },
    ogImage: '/static/insights/ownership-hosting-og.png',
  },
  'custom-website-wordpress-or-webflow': {
    hero: {
      src: '/static/insights/platform-comparison-cover.svg',
      width: 1200,
      height: 800,
      category: 'insight',
      alt: 'Cover for “Choosing between a custom website, WordPress and Webflow”: three side-by-side architecture stacks comparing the platforms.',
    },
    ogImage: '/static/insights/platform-comparison-og.png',
  },
};

/** Cover for an article slug, if one exists. */
export const insightCoverFor = (slug: string): InsightCover | undefined => INSIGHT_COVERS[slug];
